name: Java CI with Maven
run-name: Docker Build and Push to ${{ inputs.environment }}

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Int
          - E2E
          - Prod
      tag:
        description: 'Tag name for the docker image'
        required: false
        default: 'latest'
        type: string

env:
 image_name: academy
 tag_name: "${{ inputs.tag }}-${{ inputs.environment }}"
 artifact_name: artifact

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - id: set_matrix
        run: |
          MATRIX_JSON='{
            "include": [
              { "arch": "linux/arm64", "arch_name": "arm64" , "machine": "ubuntu-24.04-arm"},
              { "arch": "linux/amd64", "arch_name": "amd64" , "machine": "ubuntu-latest"}
            ]
          }'
          MATRIX_JSON=$(jq -c <<< $MATRIX_JSON)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
    
  build:
    runs-on: ${{ matrix.machine }}

    needs: matrix

    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Call Maven Build
      uses: ./.github/actions/maven_build

    - name: Call Docker Build
      id: docker_build
      uses: ./.github/actions/docker_build
      with:
        tag_name: ${{ env.tag_name }}
        image_name: ${{ env.image_name }}
        architecture: ${{ matrix.arch }}
        arch_name: ${{ matrix.arch_name }}
      
    - name: Save Docker Image
      run: |
        docker save -o ${{ env.image_name }}.tar ${{ steps.docker_build.outputs.image_exported }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: "${{ env.artifact_name }}-${{ matrix.arch_name }}"
        path: "${{ env.image_name }}.tar"

  push:
    runs-on: ubuntu-latest
    needs: 
      - build
      - matrix
    
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}

    environment: ${{ inputs.environment }} 

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: "${{ env.artifact_name }}-${{ matrix.arch_name }}"
    
    - name: Load Docker Image
      run: |
        docker load -i ${{ env.image_name }}.tar

    - name: Get Docker Image Name and save to env
      run: |
        IMAGE_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
        echo "image_generated=$IMAGE_NAME" >> $GITHUB_ENV
        docker image ls

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Push
      uses: ./.github/actions/docker_push 
      with:
        docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker_image: $image_generated